name: nyaya-langgraph
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - langgraph
      - langchain
      - langchain-core
      - langchain-openrouter
      - chromadb
      - streamlit
      - python-dotenv
      - pydantic
      - sentence-transformers
      - torchvision
      - requests
      - beautifulsoup4
      - langdetect
      - spacy
      - tqdm
      - transformers
      - accelerate
      - langchain-community
      - markdown
      - xhtml2pdf
