from __future__ import annotations

import json
import threading
import uuid
import warnings

warnings.filterwarnings("ignore")

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from nyaya_agent.graph import build_graph
from nyaya_agent.memory import ChatMemoryStore
from nyaya_agent.seed_chroma import seed_demo_corpus
from nyaya_agent.settings import CHROMA_COLLECTION, CHROMA_PERSIST_DIR, CHROMA_READY, SQLITE_PATH, setup_environment

setup_environment()

import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)
logging.getLogger("httpx").setLevel(logging.WARNING)

logger = logging.getLogger(__name__)


def _session_id() -> str:
    if "nyaya_session_id" not in st.session_state:
        # st.session_state.nyaya_session_id = str(uuid.uuid4())
        st.session_state.nyaya_session_id = 1
    return st.session_state.nyaya_session_id


def main() -> None:
    logger.info("Starting Nyaya Agent Streamlit App")
    st.set_page_config(page_title="Nyaya Agent", layout="wide")
    st.title("Nyaya Agent")
    st.caption("Case-focused chat · ChromaDB when enabled · SQLite memory (six messages + summary)")

    store = ChatMemoryStore(SQLITE_PATH)
    sid = _session_id()
    logger.info(f"Using session ID: {sid}")
    ctx = store.get_context(sid)
    logger.info(f"Loaded context for session {sid} with {len(ctx.messages)} messages")

    with st.sidebar:
        st.subheader("Status")
        st.write(f"**CHROMA_READY:** `{CHROMA_READY}`")
        st.write(f"**Chroma path:** `{CHROMA_PERSIST_DIR}`")
        st.write(f"**Collection:** `{CHROMA_COLLECTION}`")
        st.write(f"**SQLite:** `{SQLITE_PATH}`")
        if not CHROMA_READY:
            st.info("Retrieval is off. Set `CHROMA_READY=true` in `.env` after ingesting data.")
        if st.button("Seed demo Chroma documents (illustrative only)"):
            n = seed_demo_corpus()
            st.success(f"Upserted {n} demo chunks. Set `CHROMA_READY=true` and restart the app to query them.")

        st.divider()
        st.subheader("Memo Actions")
        latest_memo = st.session_state.get("latest_memo")
        if "show_memo" not in st.session_state:
            st.session_state.show_memo = False

        def toggle_memo():
            st.session_state.show_memo = not st.session_state.show_memo

        memo_btn_label = "📄 Hide Latest Memo" if st.session_state.show_memo else "📄 View Latest Memo"
        st.button(memo_btn_label, disabled=not bool(latest_memo), use_container_width=True, on_click=toggle_memo)

        if st.session_state.show_memo and latest_memo:
            def log_download():
                logger.info("User initiated download of the structured memo JSON")

            st.download_button(
                label="📥 Download JSON",
                data=json.dumps(latest_memo, indent=4),
                file_name="memo.json",
                mime="application/json",
                on_click=log_download,
                use_container_width=True
            )
            with st.expander("Memo Contents", expanded=True):
                st.json(latest_memo)

        st.divider()
        st.subheader("Context Summary")
        if ctx.summary:
            with st.expander("Summary Contents", expanded=False):
                st.markdown(ctx.summary)

    st.subheader("Chat")
    for m in ctx.messages:
        with st.chat_message(m["role"]):
            st.markdown(m["content"])

    @st.cache_resource
    def get_cached_graph():
        return build_graph()

    app = get_cached_graph()

    if prompt := st.chat_input("Ask about a case or compliance topic…"):
        logger.info(f"User entered prompt: {prompt}")
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            with st.spinner("Thinking…"):
                out = app.invoke(
                    {
                        "query": prompt,
                        "conversation_summary": ctx.summary,
                        "recent_messages": ctx.messages,
                    }
                )
            reply = (out.get("assistant_message") or out.get("chat_reply") or "").strip()
            if not reply:
                reply = json.dumps(out.get("memo") or {}, indent=2, ensure_ascii=False)[:8000]
            st.markdown(reply)
            
            if out.get("memo"):
                logger.info("New memo successfully generated by the graph")
                st.session_state.latest_memo = out["memo"]

        logger.info("Appending exchange to memory store asynchronously")
        threading.Thread(target=store.append_exchange, args=(sid, prompt, reply)).start()
        logger.info("Triggering app rerun")
        st.rerun()


if __name__ == "__main__":
    main()
